app:
  env: "development"
  port: 8080
  debug: true

mongodb:
  connection: "mongodb://r1.example.net:27017,r2.example.net:27017/"

actioncode:
  urlacm024-001: "www.placeholder.com"
  acm024-001:
    url: "h"

log:
  level: "debug"
  format: "json"